### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by drusellers** [weavejester/meta-merge#5]
```
(def defaults ^:displace {:http {:port 5000 :host "localhost" }})
(def env {:http {:port nil}})

(pprint (meta-merge defaults env))
```

output

```
{
    :http { 
       :port nil
    }
}
```

I was surprised that `nil` was all that was in the hash-map. In my mind, I wanted to see that `:port` was still set to the `default` and that `:host` was still set to `"localhost"`. I know that the goal of this project is to provide a setup similar to what `lein` has so this may very well be expected value, but you never know until you ask. 

thank you,
-d

**Comment by drusellers** [comment]
I guess it feel like i'm getting a `replace` rather than a true merge.

**Comment by weavejester** [comment]
I can see why this is a problem with how Duct uses the environment, but I think this is the correct behaviour for meta-merge. After all, `{:port nil}` isn't the same as `{}`.

Perhaps Duct should default to clearing `nil` values from the environment config map.

**Comment by drusellers** [comment]
I would enjoy the cleaning up of `nil` myself and as long as its expected behavior than I can find a way to work with it. :) 

Given that, it sounds like I need to be careful about supplying only a partial map since `meta-merge` seems to replace at the top of the hash-map rather than walking down the tree of hash-map merging keys.

Thank you for taking the time to explain this to me. :)
